#ifndef KATANA_KLEAVER_SPLASH_SCREEN_H
#define KATANA_KLEAVER_SPLASH_SCREEN_H

typedef enum
{
    SM_THIS_GAME_USES_MOUSE,
    SM_STUDIO_NAME
} SplashMessages;

#endif //KATANA_KLEAVER_SPLASH_SCREEN_H
